CREATE DATABASE IF NOT EXISTS eda_crud;
USE eda_crud;
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    email VARCHAR(180) NOT NULL UNIQUE,
    creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE USER IF NOT EXISTS 'eda_user'@'localhost' IDENTIFIED BY 'eda_password';
GRANT ALL PRIVILEGES ON eda_crud.* TO 'eda_user'@'localhost';
FLUSH PRIVILEGES;
